server:
  address: localhost
  port: 8080
spring:
  redis:
    host: ec2-43-201-59-46.ap-northeast-2.compute.amazonaws.com
    port: 6379
  servlet:
    multipart:
      maxFileSize: 50MB
      maxRequestSize: 50MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 1234
    url: jdbc:mysql://localhost:3306/bipaTV?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: root
  jpa: # https://victorydntmd.tistory.com/323
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true

  # developers.kakao?? Application ?? ?? REST API ??, RedirectURL? ?????. ??? ?????.
oauth2:
  kakao:
    token-uri: https://kauth.kakao.com/oauth/token
    resource-uri: https://kapi.kakao.com/v2/user/me
    client-id: 213b8cd0450835fc9e56958890458a96
    redirect-uri: http://localhost:8080/auth/kakao/callback
    logging:
      level:
        com.example.kakaologin: debug
  google:
    client-id: 1017186225524-ur3gd5fvh518iehnr9d68a8l0nl7op16.apps.googleusercontent.com
    client-secret: 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
    redirect-uri: http://localhost:8080/auth/google/callback
    token-uri: https://oauth2.googleapis.com/token
    resource-uri: https://www.googleapis.com/oauth2/v2/userinfo

security:
  secretKey: sdsadwqascaqwasdasfwqqgASDWQEasdgfqweghweyqwevht
cloud:
  aws:
    s3:
      bucket: streamwaves3
    stack:
      auto: false
    region:
      static: ap-northeast-2
      auto: false
    credentials:
      access-key: AKIA6ABZ54JVA3QUXWE5
      secret-key: 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
