package com.bipa4.back_bipatv.dataType;

import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor
@Getter
public enum ErrorCode {

  DELETE_ERROR("CANNOT_DELETE"),
  PRESIGNED_URL_ERROR("CANNOT_GET_PRESIGNED_URL"),
  UPLOAD_ERROR("CANNOT_UPLOAD"),
  UPDATE_ERROR("CANNOT_UPDATE"),
  LIKE_ERROR("CANNOT_LIKE"),
  UNLIKE_ERROR("CANNOT_UNLIKE"),
  VIEW_LOG_ERROR("CANNOT_UPDATE_VIEWLOG_TABLE"),
  READ_ERROR("CANNOT_READ"),
  AUTHORITY_ERROR("AUTHORITY_ERROR"),
  LOGIN_ERROR("LOGIN_ERROR"),
  LOGOUT_ERROR("LOGOUT_ERROR"),
  ACCESSTOKEN_ERROR("ACCESSTOKEN_ERROR"),
  USER_JOIN_ERROR("USER_JOIN_ERROR"),
  NO_EXIST_VIDEO("NO_EXIST_VIDEO"),
  S3_DELETE_ERROR("S3_DELETE_ERROR"),
  VIEW_LOG_CREATE_ERROR("VIEW_LOG_CREATE_ERROR"),
  CATEGORY_CREATE_ERROR("CATEGORY_CREATE_ERROR"),
  CANNOT_UNLIKE_ERROR("CANNOT_UNLIKE_ERROR"),
  INSERT_ERROR("INSERT_ERROR"),
  INSERT_DTO_ERROR("INSERT_DTO_ERROR");

  private final String code;
}
